### ISSUE TITLE
Cant install some apps (infinite loading), how to know what happened?

### ISSUE THREAD

**Issue by joseehilton147** [weareblahs/WSAUtilities#11]
Im trying to install some apps, but someone's keep loading infinite... how to debug it to know what happened?

15min on this screen (tiktok) -> [Source APK](https://tiktok.br.uptodown.com/android)
![image](https://user-images.githubusercontent.com/53986027/145433192-b7059118-78e8-4729-956c-23722b7e1c00.png)

but on spotify install instantly

ps: its working on some apps, so isnt a installation error, like i said, on spotify works.

**Comment by weareblahs** [comment]
Not the right repository. You might need to ask this question on https://github.com/Simizfo/WSATools/issues.
