### ISSUE TITLE
Cannot connect to WSA. Make sure ADB is enabled in the Windows Subsystem for Android settings app and retry.

### ISSUE THREAD

**Issue by Tiwas** [weareblahs/WSAUtilities#4]
I hope this is an ok question to ask for help with, as there didn't seem to be any wiki entries. I've tried connecting manually, too, with "adb connect localhost:58526" from the directory I installed adb with this app. Developer mode is enabled.

Any tips?

Thanks!

**Comment by weareblahs** [comment]
`localhost:58526` is the default IP of WSA - maybe the WSA stuffs didn't start to run. Try running Amazon Appstore or other apps then try again - the ADB thing should be initialized by WSA at that point.

**Comment by henfri** [comment]
Hello,

I am having a similar/the same issue.
I started Amazon Appstore (which is in the end not available in my country, but it makes sure WSA is running before.

> Windows Subsystem for Android app installer
> This script uses adb and simplifies installation for APK files on WSA.
> Before you start, please ensure that you toggled "Developer Mode" on in WSA settings.
> Done? then press any key to continue the process.
> Drag and drop your APK file here / type in the path here then press "Enter":"E:\WSATools_v0.0.8_22000.346\Cornelsen Lernen_v2.1.0_apkpure.com.apk"
> cannot connect to 127.0.0.1:58526: Connection refused (10061)
> The system could not find the specified file
> error: no devices/emulators found
> Performing Push Install
> adb: error: failed to get feature set: no devices/emulators found
> Installation complete!
> Do you want to install other APK files? [Yes / (No)]:

Do you have any Idea for us?

Thanks,
Hendrik

**Comment by henfri** [comment]
P.S: In other tutorials I see:
> Open Start.
> Search for Windows Subsystem for Android and click the top result to open the platform.
> Turn on the Developer mode toggle switch.

In Start I do not find "Windows Subsystem for Android".

**Comment by weareblahs** [comment]
Actually, that's called "Windows Subsystem for Android™ Settings" now.

Also, make sure that you do these at the settings before launching an app to trigger the ADB stuff:
![image](https://user-images.githubusercontent.com/37889443/142762709-10ef9f1b-fded-4ad0-9ed1-4bdd9e757757.png)

**Comment by henfri** [comment]
Hello,
ok, that helped. 

Now I get
```
failed to authenticate to localhost:58526
The system could not find the specified file
Performing Streamed Install
adb: failed to stat base.apk: No such file or directory
Installation complete!
```
Note that the file I wanted to install was NOT called base.apk.

Connection works though:
```
E:\WSATools_v0.0.8_22000.346\main>adb connect localhost:58526
already connected to localhost:58526

E:\WSATools_v0.0.8_22000.346\main>adb devices
List of devices attached
localhost:58526 device
```

Thanks for your help,
Hendrik

**Comment by weareblahs** [comment]
> Note that the file I wanted to install was NOT called base.apk.

All files are renamed to `base.apk` before installing to avoid future errors with some spacing stuffs. Also, I found out an error that caused this. Follow these instructions to apply the fix:

 - Download `patch_0.0.8.bat` from https://github.com/weareblahs/WSAtools/releases/download/beta-0.0.8/patch_0.0.8.bat.
 - Copy this file to the WSATools directory (for your case, you have to copy it to `E:\WSATools_v0.0.8_22000.346\`)
 - Run this file.
 - Run InstallAPK again.

**Comment by henfri** [comment]
Hi,
thanks, I was just looking at those lines of codes and was going to hint you at this :-)
It works!

Thanks!

A last newbie question: How can I run this app now?

Best regards,
Hendrik

**Comment by weareblahs** [comment]
Go to start menu, then find the app name. Just like you would in any Windows app.

**Comment by henfri** [comment]
Thanks. That brilliant!
