### ISSUE TITLE
winver too restrictive

### ISSUE THREAD

**Issue by henfri** [weareblahs/WSAUtilities#5]
**Is your feature request related to a problem? Please describe.**
Would be nice if further windows versions would be supported

**Describe the solution you'd like**
I use the script on 22000.348 successfully (having patched the *.bat)

But maybe it would work on 318 as well... I will check if I can check.

Best regards,
Hendrik

**Comment by weareblahs** [comment]
Just curious - is there any way to let command prompt detect something like this:
`Microsoft Windows [Version 10.0.22000.348]` but it detects 22000 only.

Here's the excerpt from the original script:
```batch
if %check% == 10.0.22000.348 (
:: Success screen
  cls
  echo Windows version up-to-date, which means it supports Windows Subsystem for Android. 
  echo Launching in 3 seconds...
  timeout 1 > NUL
  cls
  echo Windows version up-to-date, which means it supports Windows Subsystem for Android. 
  echo Launching in 2 seconds...
  timeout 1 > NUL
  cls
  echo Windows version up-to-date, which means it supports Windows Subsystem for Android. 
  echo Launching in 1 seconds...
  timeout 1 > NUL
  del checkver.bat
  cls
  cd main
  WSATools
  pause >nul
```

Wonder that can I just simply change `if %check% == 10.0.22000.348 (` to `if %check% == *22000* (`. I'm not sure about this kind of stuffs on command prompt

**Comment by henfri** [comment]
Maybe something like this:
@echo off & setlocal

for %%a in (%check%) do 
if %%a ==22000
...

**Comment by henfri** [comment]
No, that only works if it is space separated.

then more like this one:
```
for /f "tokens=2 delims=_" %%a in ("%STRING%") do (
  set AFTER_UNDERSCORE=%%a
)
```


Or:
%check% == 10.0.22000.348
echo %check:~5,5%
should give 22000

Best regards,
Hendrik

**Comment by weareblahs** [comment]
I think it should be working properly to detect all Win11 versions after changing to this:
```batch
for /f %%N in ('checkver') do set "check=%%N"
for /f %%N in ('echo %check:~5,5%') do set "check2=%%N"
if %check2% == 22000 (
:: Success screen
```

Thanks. Will use this at v0.0.8b, which will be published later.
